<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-USCISFormTracker.Emailer-4ceb9d5a-8b18-491d-8072-e176e7d45b6d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\USCISFormTracker.Core\USCISFormTracker.Core.csproj" />
    <ProjectReference Include="..\USCISFormTracker.Dto\USCISFormTracker.Dto.csproj" />
  </ItemGroup>
</Project>
