// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using USCISFormTracker.Data;

#nullable disable

namespace USCISFormTracker.Data.Migrations
{
    [DbContext(typeof(FormTrackerDbContext))]
    [Migration("20251119000000_AddPdfPathTracking")]
    partial class AddPdfPathTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("USCISFormTracker.Core.Models.PdfFormChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DetectedChangeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiffLinesSerialized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewPdfPath")
                        .HasColumnType("text");

                    b.Property<string>("OldHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldPdfPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FormChanges");
                });

            modelBuilder.Entity("USCISFormTracker.Core.Models.PdfFormRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestPdfPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("FormRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
